name: CI-pipeline for raffaelo framework

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:

  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip3 install -r requirements-dev.txt

      - name: Pre-commit run
        run: pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip3 install -r requirements-dev.txt

      - name: Install raffaelo-uniswap-v3
        run: pip3 install -e "git+https://github.com/e183b796621afbf902067460/raffaelo.git#egg=raffaelo_uniswap_v3&subdirectory=_modules/raffaelo-uniswap-v3/" --config-settings editable_mode=strict

      - name: Install raffaelo-quickswap-v3
        run: pip3 install -e "git+https://github.com/e183b796621afbf902067460/raffaelo.git#egg=raffaelo_quickswap_v3&subdirectory=_modules/raffaelo-quickswap-v3/" --config-settings editable_mode=strict

      - name: Pytest run raffaelo/ with coverage
        run: coverage run -m pytest tests/

      - name: Pytest run raffaelo-uniswap-v3/ with coverage
        run: coverage run -m pytest _modules/raffaelo-uniswap-v3/raffaelo_uniswap_v3_tests/

      - name: Pytest run raffaelo-quickswap-v3/ with coverage
        run: coverage run -m pytest _modules/raffaelo-quickswap-v3/raffaelo_quickswap_v3_tests/

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v2
