name: CI-pipeline for raffaelo framework

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip3 install -r requirements-dev.txt
  
  isort:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: Run isort
        run: isort --check .

  ruff:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: Run ruff
        run: ruff check

  black:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: Run black
        run: black --check .

  pytest:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: pytest tests/
